export const Routes={
    User_Login:'User_Login',
    Register:'Register',
    Job : 'Job',
    Profile:'Profile',
    SavedJob:'SavedJob',
    Job : 'Job',
    PostJob : 'PostJob',
    ViewJobPost: 'ViewJobPost',
    ApplyJob:'ApplyJob',
    JobPostDetails:'JobPostDetails',
    ApplicationStatus:'Application Status',
    ViewPostDetails:'ViewPostDetails',
    JobPostStatus:'JobPostStatus',
}