export const Routes={
    User_Login:'User_Login',
    Register:'Register',
    Job : 'Job',
    Profile:'Profile',
    SavedJob:'Saved Job',
    Job : 'Job',
    PostJob : 'Post Job',
    ViewJobPost: 'View JobPost',
    ApplyJob:'ApplyJob',
    JobPostDetails:'JobPostDetails',
    ApplicationStatus:'Application Status',
    ViewPostDetails:'ViewPostDetails',
    JobPostStatus:'JobPostStatus',
    CreateTeam:'Create Team',
    JoinTeam:'Join Team',
}